from .identifiable import Identifiable
from .animal import Animal
from .river_dolphin import RiverDolphin
from .kikakapu import Kikakapu
from .gecko import Gecko
from .happy_spider import HappySpider
from .nene_goose import NeneGoose
from .opeapea import OpeApeA
from .pueo import Pueo
from .ulae import Ulae
